### ISSUE TITLE
Prettier, more informative error pages

### ISSUE THREAD

**Issue by bitemyapp** [alexeyzab/cards-with-comrades#8]

**Comment by alexeyzab** [comment]
@bitemyapp Looks like this now:
![error404](https://cloud.githubusercontent.com/assets/5606260/22631055/f1edf2a8-ebd3-11e6-9f4a-6755c2cf29cb.png)

Let me know what you think. I've left the old `errorFragment'` just in case. Probably should start working in a separate branch. :thinking:

**Comment by bitemyapp** [comment]
@alexeyzab I agree branch discipline is a better idea going forward, but don't worry about it for whatever's already done or in flight.

Recommend deleting dead code, git has history if we need it again.

**Comment by bitemyapp** [comment]
New pages look good, I'd say close this issue when it hits `master`.

**Comment by alexeyzab** [comment]
@bitemyapp Gotcha, will clean up and close this now.
